# Generated by Django 3.2.23 on 2024-01-28 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('enrollment_number', models.BigIntegerField()),
                ('bio', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Mechanical Engineering', 'Mechanical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Electronics', 'Electronics')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_related', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_related', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user3_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
