# Generated by Django 3.2.23 on 2024-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoices',
            name='gender',
            field=models.CharField(default='Rather not say', max_length=20),
        ),
    ]
