# Generated by Django 3.2.23 on 2024-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userchoices_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='enrollment_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
