# Generated by Django 3.2.23 on 2024-01-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_userchoices_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], default='Rather not say', max_length=20),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='status',
            field=models.CharField(choices=[('Long Distance', 'Long Distance'), ('Dating', 'Dating'), ('Single', 'Single')], max_length=100),
        ),
    ]
