# Generated by Django 3.2.23 on 2024-01-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20240129_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='branch',
            field=models.CharField(choices=[('Mechanical Engineering', 'Mechanical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Electronics', 'Electronics'), ('Civil Engineering', 'Civil Engineering'), ('Economics', 'Economics'), ('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Eph', 'Eph'), ('Mathematics and Computing', 'Mathematics and Computing'), ('GPT', 'GPT'), ('GT', 'GT'), ('Metallurgy', 'Metallurgy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='status',
            field=models.CharField(choices=[('Dating', 'Dating'), ('Single', 'Single'), ('Long Distance', 'Long Distance')], max_length=100),
        ),
    ]
