# Generated by Django 3.2.23 on 2024-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20240129_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoices',
            name='userphoto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
