# Generated by Django 3.2.23 on 2024-01-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_userchoices_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='userphoto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
