# Generated by Django 3.2.23 on 2024-01-25 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Socially', '0022_auto_20240126_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 25, 23, 34, 31, 204691, tzinfo=utc), null=True),
        ),
    ]
